# Gapps inclusion makefile
PRODUCT_COPY_FILES += \
    vendor/matricom/prebuilt/gapps/addon.d/70-gapps.sh:system/addon.d/70-gapps.sh \
    vendor/matricom/prebuilt/gapps/app/ChromeBookmarksSyncAdapter.apk:system/app/ChromeBookmarksSyncAdapter.apk \
    vendor/matricom/prebuilt/gapps/app/ConfigUpdater.apk:system/app/ConfigUpdater.apk \
    vendor/matricom/prebuilt/gapps/app/GenieWidget.apk:system/app/GenieWidget.apk \
    vendor/matricom/prebuilt/gapps/app/Gmail.apk:system/app/Gmail.apk \
    vendor/matricom/prebuilt/gapps/app/GmsCore.apk:system/app/GmsCore.apk \
    vendor/matricom/prebuilt/gapps/app/GoogleBackupTransport.apk:system/app/GoogleBackupTransport.apk \
    vendor/matricom/prebuilt/gapps/app/GoogleCalendarSyncAdapter.apk:system/app/GoogleCalendarSyncAdapter.apk \
    vendor/matricom/prebuilt/gapps/app/GoogleContactsSyncAdapter.apk:system/app/GoogleContactsSyncAdapter.apk \
    vendor/matricom/prebuilt/gapps/app/GoogleEars.apk:system/app/GoogleEars.apk \
    vendor/matricom/prebuilt/gapps/app/GoogleFeedback.apk:system/app/GoogleFeedback.apk \
    vendor/matricom/prebuilt/gapps/app/GoogleLoginService.apk:system/app/GoogleLoginService.apk \
    vendor/matricom/prebuilt/gapps/app/GooglePartnerSetup.apk:system/app/GooglePartnerSetup.apk \
    vendor/matricom/prebuilt/gapps/app/GooglePlus.apk:system/app/GooglePlus.apk \
    vendor/matricom/prebuilt/gapps/app/GoogleServicesFramework.apk:system/app/GoogleServicesFramework.apk \
    vendor/matricom/prebuilt/gapps/app/GoogleTTS.apk:system/app/GoogleTTS.apk \
    vendor/matricom/prebuilt/gapps/app/LatinImeDictionaryPack.apk:system/app/LatinImeDictionaryPack.apk \
    vendor/matricom/prebuilt/gapps/app/MediaUploader.apk:system/app/MediaUploader.apk \
    vendor/matricom/prebuilt/gapps/app/NetworkLocation.apk:system/app/NetworkLocation.apk \
    vendor/matricom/prebuilt/gapps/app/OneTimeInitializer.apk:system/app/OneTimeInitializer.apk \
    vendor/matricom/prebuilt/gapps/app/Phonesky.apk:system/app/Phonesky.apk \
    vendor/matricom/prebuilt/gapps/app/QuickSearchBox.apk:system/app/QuickSearchBox.apk \
    vendor/matricom/prebuilt/gapps/app/TalkBack.apk:system/app/TalkBack.apk \
    vendor/matricom/prebuilt/gapps/app/VoiceSearchStub.apk:system/app/VoiceSearchStub.apk \
    vendor/matricom/prebuilt/gapps/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
    vendor/matricom/prebuilt/gapps/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml \
    vendor/matricom/prebuilt/gapps/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
    vendor/matricom/prebuilt/gapps/etc/permissions/features.xml:system/etc/permissions/features.xml \
    vendor/matricom/prebuilt/gapps/etc/preferred-apps/google.xml:system/etc/preferred-apps/google.xml \
    vendor/matricom/prebuilt/gapps/etc/g.prop:system/etc/g.prop \
    vendor/matricom/prebuilt/gapps/framework/com.google.android.maps.jar:system/framework/com.google.android.maps.jar \
    vendor/matricom/prebuilt/gapps/framework/com.google.android.media.effects.jar:system/framework/com.google.android.media.effects.jar \
    vendor/matricom/prebuilt/gapps/framework/com.google.widevine.software.drm.jar:system/framework/com.google.widevine.software.drm.jar \
    vendor/matricom/prebuilt/gapps/lib/libAppDataSearch.so:system/lib/libAppDataSearch.so \
    vendor/matricom/prebuilt/gapps/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so \
    vendor/matricom/prebuilt/gapps/lib/libfrsdk.so:system/lib/libfrsdk.so \
    vendor/matricom/prebuilt/gapps/lib/libgames_rtmp_jni.so:system/lib/libgames_rtmp_jni.so \
    vendor/matricom/prebuilt/gapps/lib/libgcomm_jni.so:system/lib/libgcomm_jni.so \
    vendor/matricom/prebuilt/gapps/lib/libgoogle_recognizer_jni.so:system/lib/libgoogle_recognizer_jni.so \
    vendor/matricom/prebuilt/gapps/lib/libgoogle_recognizer_jni_l.so:system/lib/libgoogle_recognizer_jni_l.so \
    vendor/matricom/prebuilt/gapps/lib/libgtalk_jni.so:system/lib/libgtalk_jni.so \
    vendor/matricom/prebuilt/gapps/lib/libgtalk_stabilize.so:system/lib/libgtalk_stabilize.so \
    vendor/matricom/prebuilt/gapps/lib/libjni_latinime.so:system/lib/libjni_latinime.so \
    vendor/matricom/prebuilt/gapps/lib/libpatts_engine_jni_api.so:system/lib/libpatts_engine_jni_api.so \
    vendor/matricom/prebuilt/gapps/lib/libplus_jni_v8.so:system/lib/libplus_jni_v8.so \
    vendor/matricom/prebuilt/gapps/lib/librs.antblur.so:system/lib/librs.antblur.so \
    vendor/matricom/prebuilt/gapps/lib/librs.antblur_constant.so:system/lib/librs.antblur_constant.so \
    vendor/matricom/prebuilt/gapps/lib/librs.antblur_drama.so:system/lib/librs.antblur_drama.so \
    vendor/matricom/prebuilt/gapps/lib/librs.drama.so:system/lib/librs.drama.so \
    vendor/matricom/prebuilt/gapps/lib/librs.film_base.so:system/lib/librs.film_base.so \
    vendor/matricom/prebuilt/gapps/lib/librs.fixedframe.so:system/lib/librs.fixedframe.so \
    vendor/matricom/prebuilt/gapps/lib/librs.grey.so:system/lib/librs.grey.so \
    vendor/matricom/prebuilt/gapps/lib/librs.image_wrapper.so:system/lib/librs.image_wrapper.so \
    vendor/matricom/prebuilt/gapps/lib/librs.retrolux.so:system/lib/librs.retrolux.so \
    vendor/matricom/prebuilt/gapps/lib/librsjni.so:system/lib/librsjni.so \
    vendor/matricom/prebuilt/gapps/lib/libRSSupport.so:system/lib/libRSSupport.so \
    vendor/matricom/prebuilt/gapps/lib/libspeexwrapper.so:system/lib/libspeexwrapper.so \
    vendor/matricom/prebuilt/gapps/lib/libvcdecoder_jni.so:system/lib/libvcdecoder_jni.so \
    vendor/matricom/prebuilt/gapps/lib/libvorbisencoder.so:system/lib/libvorbisencoder.so \
    vendor/matricom/prebuilt/gapps/lib/libwebp_android.so:system/lib/libwebp_android.so \
    vendor/matricom/prebuilt/gapps/tts/lang_pico/de-DE_gl0_sg.bin:system/tts/lang_pico/de-DE_gl0_sg.bin \
    vendor/matricom/prebuilt/gapps/tts/lang_pico/de-DE_ta.bin:system/tts/lang_pico/de-DE_ta.bin \
    vendor/matricom/prebuilt/gapps/tts/lang_pico/es-ES_ta.bin:system/tts/lang_pico/es-ES_ta.bin \
    vendor/matricom/prebuilt/gapps/tts/lang_pico/es-ES_zl0_sg.bin:system/tts/lang_pico/es-ES_zl0_sg.bin \
    vendor/matricom/prebuilt/gapps/tts/lang_pico/fr-FR_nk0_sg.bin:system/tts/lang_pico/fr-FR_nk0_sg.bin \
    vendor/matricom/prebuilt/gapps/tts/lang_pico/fr-FR_ta.bin:system/tts/lang_pico/fr-FR_ta.bin \
    vendor/matricom/prebuilt/gapps/tts/lang_pico/it-IT_cm0_sg.bin:system/tts/lang_pico/it-IT_cm0_sg.bin \
    vendor/matricom/prebuilt/gapps/tts/lang_pico/it-IT_ta.bin:system/tts/lang_pico/it-IT_ta.bin \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/acoustic_model:system/usr/srec/en-US/acoustic_model \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/c_fst:system/usr/srec/en-US/c_fst \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/clg:system/usr/srec/en-US/clg \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/compile_grammar.config:system/usr/srec/en-US/compile_grammar.config \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/contacts.abnf:system/usr/srec/en-US/contacts.abnf \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/dict:system/usr/srec/en-US/dict \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/dictation.config:system/usr/srec/en-US/dictation.config \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/embed_phone_nn_model:system/usr/srec/en-US/embed_phone_nn_model \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/embed_phone_nn_state_sym:system/usr/srec/en-US/embed_phone_nn_state_sym \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/endpointer_dictation.config:system/usr/srec/en-US/endpointer_dictation.config \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/endpointer_voicesearch.config:system/usr/srec/en-US/endpointer_voicesearch.config \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/ep_acoustic_model:system/usr/srec/en-US/ep_acoustic_model \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/g2p_fst:system/usr/srec/en-US/g2p_fst \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/google_hotword.config:system/usr/srec/en-US/google_hotword.config \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/google_hotword_clg:system/usr/srec/en-US/google_hotword_clg \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/google_hotword_logistic:system/usr/srec/en-US/google_hotword_logistic \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/grammar.config:system/usr/srec/en-US/grammar.config \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/hmmsyms:system/usr/srec/en-US/hmmsyms \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/hotword_symbols:system/usr/srec/en-US/hotword_symbols \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/lintrans_model:system/usr/srec/en-US/lintrans_model \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/metadata:system/usr/srec/en-US/metadata \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/normalizer:system/usr/srec/en-US/normalizer \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/norm_fst:usr/srec/en-US/norm_fst/usr/srec/en-US/norm_fst \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/offensive_word_normalizer:system/usr/srec/en-US/offensive_word_normalizer \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/phonelist:system/usr/srec/en-US/phonelist \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/rescoring_lm:system/usr/srec/en-US/rescoring_lm \
    vendor/matricom/prebuilt/gapps/usr/srec/en-US/symbols:system/usr/srec/en-US/symbols



