#!/bin/bash

date=`date +"%m_%d_%Y"`
changelog=
repo forall -c '
    sdate=
    project=`repo info . | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | grep Project`
    project_short=`echo "$project" | cut -f2 -d " "`
    private=`grep "$project_short" /Users/khasmek/Android/matricom/.repo/manifest.xml | grep private` 
    log=`git log --pretty="%h - %s (%cn)" --no-merges --since=$sdate --date-order`
    if [ -n "$log" ] && [ -z "$private" ]; then
        echo "## **$project**"
        echo "---"
        echo "$log" | while read line
        do
            id=`echo "$line" | cut -f1 -d " "`
            title=`echo "$line" | cut -f2 -d "-"`
            echo "[$id](http://github.com/Matricom/$project_short/commit/$id) -$title"
            #echo "$line"
            echo ""
        done
        echo ""
    fi
'  > "$changelog"_"$date".md
