#!/bin/bash

if [ ! -z $OUT_DIR_COMMON_BASE ]; then
    TREE_NAME=`basename $ANDROID_BUILD_TOP`
    OUT_DIR=$OUT_DIR_COMMON_BASE/$TREE_NAME
else
    OUT_DIR=$ANDROID_BUILD_TOP/out
fi

# manipulate TARGET_PRODUCT to give us just device
DEVICE=${TARGET_PRODUCT##*_}

FIRMWARE_REVISION=`cat ${OUT_DIR}/target/product/${DEVICE}/system/build.prop | grep ro.matricom.firmware.version | cut -f2 -d "="`
if [ ! -z $VENDOR_OVERLAY ]; then
    PRODUCT=${VENDOR_OVERLAY}_${DEVICE}
else
    PRODUCT=${TARGET_PRODUCT}
fi

# cat all the install info > $OUT_DIR/factory_update_params.aml
cat >${OUT_DIR}/target/product/${DEVICE}/factory_update_param.aml <<EOL
--show_text
--update_package=/external_sd/${PRODUCT}_${FIRMWARE_REVISION}.zip
--run_command=/system/bin/reboot
EOL
