#!/bin/bash
#set -x
# OTA package util
# Takes otapackage, factory_update_param.aml, and recovery image
# and creates ${DEVICE}_${DATE}_${FIRMWARE_REV}.zip
#
# g18ref -> propped to mx2
#
# This script will be called from squisher and opticharger as last stop
# if firmware ota package is desired - compile time call
QUIET=-q
TOP=${ANDROID_BUILD_TOP}
# matricom device name
VERSION=${TARGET_PRODUCT##*_}
OUT=${TOP}/out/target/product/${VERSION}
VENDOR=${TOP}/vendor/matricom
DATE=`date +%Y%m%d`
FIRMWARE_REV=

if [ "$TARGET_BUILD_VARIANT" = "userdebug" ]; then
    OTAPACKAGE=$OUT/${TARGET_PRODUCT}-ota-eng.$DATE.zip
else
    OTAPACKAGE=$OUT/${TARGET_PRODUCT}-ota-$DATE.zip
fi

if [ ! -f "$OTAPACKAGE" ]; then
    echo "$OTAPACKAGE doesn't exist!"
    exit 1
fi

REPACK=$OUT/repack.d
OTAPACK=$OUT/ota.d
rm -rf $REPACK
rm -rf $OTAPACK
mkdir -p $REPACK
mkdir -p $OTAPACK
echo

mkdir $REPACK/ota
(
cd $REPACK/ota
echo "Unpacking $OTAPACKAGE..."
unzip $QUIET $OTAPACKAGE
echo
)

# Grab firmware revision
#FIRMWARE_REV=`sed -n -e'/ro.matricom.firmware.version/s/^.*=//p' $REPACK/ota/system/build.prop
FIRMWARE_REV=1.1.6

# Rename and copy over $OTAPACKAGE to $OTAPACK
cp $OTAPACKAGE $OTAPACK/
# Strip directory from OTAPACKAGE
OTAPACKAGE=${OTAPACKAGE##*/}
# if VERSION is g18ref reprop to mx2
if [ $VERSION == "g18ref" ]; then
    VERSION=mx2
fi

mv $OTAPACK/$OTAPACKAGE $OTAPACK/${VERSION}.zip

# Copy over factory_update_param.aml and recovery.img
cp ${VENDOR}/prebuilt/ota/factory_update_param.aml $OTAPACK/
cp $OUT/recovery.img $OTAPACK/

#change param --update_package to match VERSION (our product name for device i.e mx2 vs g18ref)
sed -i 's/^--update_package=*/--update_package=\/sdcard\/'$VERSION'update.zip/g' $OTAPACK/factory_update_param.aml

# Pack it up
echo -e "Zipping package..."
OTA_VERSION=${VERSION}_${DATE}_${FIRMWARE_REV}
( cd $OTAPACK; zip $QUIET -r ${OTA_VERSION}.zip . )
mv $OTAPACK/${OTA_VERSION}.zip $OUT/
echo

# Clean up
echo "Cleaning up..."
rm -rf $REPACK
rm -rf $OTAPACK
echo

echo "OTA packaging complete"
echo
echo "OTA: $OUT/${OTA_VERSION}.zip"
